In [1]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [31]:
#your code here

with open('player_data.json') as json_file:
    data = json.load(json_file)

In [33]:
data[0]

{'PERSON_ID': 203518,
 'FIRST_NAME': 'Alex',
 'LAST_NAME': 'Abrines',
 'DISPLAY_FIRST_LAST': 'Alex Abrines',
 'DISPLAY_LAST_COMMA_FIRST': 'Abrines, Alex',
 'DISPLAY_FI_LAST': 'A. Abrines',
 'BIRTHDATE': '1993-08-01T00:00:00',
 'SCHOOL': ' ',
 'COUNTRY': 'Spain',
 'LAST_AFFILIATION': 'Spain/Spain',
 'HEIGHT': '',
 'WEIGHT': '',
 'SEASON_EXP': 2,
 'JERSEY': '',
 'POSITION': '',
 'ROSTERSTATUS': 'Inactive',
 'TEAM_ID': 0,
 'TEAM_NAME': '',
 'TEAM_ABBREVIATION': '',
 'TEAM_CODE': '',
 'TEAM_CITY': '',
 'PLAYERCODE': 'alex_abrines',
 'FROM_YEAR': 2016,
 'TO_YEAR': 2018,
 'DLEAGUE_FLAG': 'N',
 'NBA_FLAG': 'Y',
 'GAMES_PLAYED_FLAG': 'Y',
 'DRAFT_YEAR': '2013',
 'DRAFT_ROUND': '2',
 'DRAFT_NUMBER': '32',
 'CAREER_STATS': {'PTS': 5.3,
  'AST': 0.5,
  'REB': 1.4,
  'ALL_STAR_APPEARANCES': 0},
 'GAMELOG': [{'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800772',
   'GAME_DATE': 'FEB 01, 2019',
   'MATCHUP': 'OKC @ MIA',
   'WL': 'W',
   'MIN': 9,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800751',
   'GAME_DATE': 'JAN 29, 2019',
   'MATCHUP': 'OKC @ ORL',
   'WL': 'W',
   'MIN': 6,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800493',
   'GAME_DATE': 'DEC 23, 2018',
   'MATCHUP': 'OKC vs. MIN',
   'WL': 'L',
   'MIN': 27,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 2,
   'PTS': 7,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800485',
   'GAME_DATE': 'DEC 22, 2018',
   'MATCHUP': 'OKC @ UTA',
   'WL': 'W',
   'MIN': 16,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 6,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800466',
   'GAME_DATE': 'DEC 19, 2018',
   'MATCHUP': 'OKC @ SAC',
   'WL': 'W',
   'MIN': 23,
   'FGM': 3,
   'FGA': 7,
   'FG_PCT': 0.429,
   'FG3M': 3,
   'FG3A': 7,
   'FG3_PCT': 0.429,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 9,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800447',
   'GAME_DATE': 'DEC 17, 2018',
   'MATCHUP': 'OKC vs. CHI',
   'WL': 'W',
   'MIN': 14,
   'FGM': 3,
   'FGA': 4,
   'FG_PCT': 0.75,
   'FG3M': 2,
   'FG3A': 3,
   'FG3_PCT': 0.667,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 2,
   'DREB': 1,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 8,
   'PLUS_MINUS': 4,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800434',
   'GAME_DATE': 'DEC 15, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 6,
   'PLUS_MINUS': 7,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800426',
   'GAME_DATE': 'DEC 14, 2018',
   'MATCHUP': 'OKC @ DEN',
   'WL': 'L',
   'MIN': 19,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800411',
   'GAME_DATE': 'DEC 12, 2018',
   'MATCHUP': 'OKC @ NOP',
   'WL': 'L',
   'MIN': 14,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 5,
   'PLUS_MINUS': 0,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800396',
   'GAME_DATE': 'DEC 10, 2018',
   'MATCHUP': 'OKC vs. UTA',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -12,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800373',
   'GAME_DATE': 'DEC 07, 2018',
   'MATCHUP': 'OKC @ CHI',
   'WL': 'L',
   'MIN': 15,
   'FGM': 1,
   'FGA': 4,
   'FG_PCT': 0.25,
   'FG3M': 1,
   'FG3A': 4,
   'FG3_PCT': 0.25,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 3,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 3,
   'PTS': 3,
   'PLUS_MINUS': -15,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800358',
   'GAME_DATE': 'DEC 05, 2018',
   'MATCHUP': 'OKC @ BKN',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 3,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -10,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800343',
   'GAME_DATE': 'DEC 03, 2018',
   'MATCHUP': 'OKC @ DET',
   'WL': 'W',
   'MIN': 18,
   'FGM': 1,
   'FGA': 3,
   'FG_PCT': 0.333,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800325',
   'GAME_DATE': 'NOV 30, 2018',
   'MATCHUP': 'OKC vs. ATL',
   'WL': 'W',
   'MIN': 26,
   'FGM': 7,
   'FGA': 11,
   'FG_PCT': 0.636,
   'FG3M': 7,
   'FG3A': 11,
   'FG3_PCT': 0.636,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 21,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800313',
   'GAME_DATE': 'NOV 28, 2018',
   'MATCHUP': 'OKC vs. CLE',
   'WL': 'W',
   'MIN': 27,
   'FGM': 1,
   'FGA': 9,
   'FG_PCT': 0.111,
   'FG3M': 1,
   'FG3A': 8,
   'FG3_PCT': 0.125,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 2,
   'REB': 3,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 3,
   'PLUS_MINUS': 13,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800282',
   'GAME_DATE': 'NOV 24, 2018',
   'MATCHUP': 'OKC vs. DEN',
   'WL': 'L',
   'MIN': 8,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 0,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800274',
   'GAME_DATE': 'NOV 23, 2018',
   'MATCHUP': 'OKC vs. CHA',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 0,
   'PLUS_MINUS': 1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800209',
   'GAME_DATE': 'NOV 14, 2018',
   'MATCHUP': 'OKC vs. NYK',
   'WL': 'W',
   'MIN': 7,
   'FGM': 0,
   'FGA': 2,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 3,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800196',
   'GAME_DATE': 'NOV 12, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 20,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 2,
   'STL': 2,
   'BLK': 1,
   'TOV': 1,
   'PF': 4,
   'PTS': 8,
   'PLUS_MINUS': -11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800181',
   'GAME_DATE': 'NOV 10, 2018',
   'MATCHUP': 'OKC @ DAL',
   'WL': 'L',
   'MIN': 26,
   'FGM': 2,
   'FGA': 6,
   'FG_PCT': 0.333,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800163',
   'GAME_DATE': 'NOV 08, 2018',
   'MATCHUP': 'OKC vs. HOU',
   'WL': 'W',
   'MIN': 19,
   'FGM': 0,
   'FGA': 3,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 3,
   'REB': 4,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 1,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': -8,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800153',
   'GAME_DATE': 'NOV 07, 2018',
   'MATCHUP': 'OKC @ CLE',
   'WL': 'W',
   'MIN': 26,
   'FGM': 3,
   'FGA': 12,
   'FG_PCT': 0.25,
   'FG3M': 3,
   'FG3A': 10,
   'FG3_PCT': 0.3,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 1,
   'BLK': 0,
   'TOV': 0,
   'PF': 1,
   'PTS': 9,
   'PLUS_MINUS': 11,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800144',
   'GAME_DATE': 'NOV 05, 2018',
   'MATCHUP': 'OKC vs. NOP',
   'WL': 'W',
   'MIN': 30,
   'FGM': 2,
   'FGA': 4,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 4,
   'REB': 4,
   'AST': 3,
   'STL': 0,
   'BLK': 0,
   'TOV': 1,
   'PF': 1,
   'PTS': 7,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800119',
   'GAME_DATE': 'NOV 02, 2018',
   'MATCHUP': 'OKC @ WAS',
   'WL': 'W',
   'MIN': 24,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 2,
   'TOV': 0,
   'PF': 3,
   'PTS': 8,
   'PLUS_MINUS': 27,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800111',
   'GAME_DATE': 'NOV 01, 2018',
   'MATCHUP': 'OKC @ CHA',
   'WL': 'W',
   'MIN': 30,
   'FGM': 9,
   'FGA': 15,
   'FG_PCT': 0.6,
   'FG3M': 5,
   'FG3A': 10,
   'FG3_PCT': 0.5,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 4,
   'PTS': 25,
   'PLUS_MINUS': 16,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800103',
   'GAME_DATE': 'OCT 30, 2018',
   'MATCHUP': 'OKC vs. LAC',
   'WL': 'W',
   'MIN': 15,
   'FGM': 1,
   'FGA': 2,
   'FG_PCT': 0.5,
   'FG3M': 1,
   'FG3A': 1,
   'FG3_PCT': 1.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 0,
   'REB': 0,
   'AST': 0,
   'STL': 4,
   'BLK': 1,
   'TOV': 1,
   'PF': 5,
   'PTS': 3,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800085',
   'GAME_DATE': 'OCT 28, 2018',
   'MATCHUP': 'OKC vs. PHX',
   'WL': 'W',
   'MIN': 24,
   'FGM': 0,
   'FGA': 5,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 2,
   'FTA': 2,
   'FT_PCT': 1.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 0,
   'STL': 2,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 2,
   'PLUS_MINUS': -1,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800065',
   'GAME_DATE': 'OCT 25, 2018',
   'MATCHUP': 'OKC vs. BOS',
   'WL': 'L',
   'MIN': 19,
   'FGM': 2,
   'FGA': 5,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 5,
   'FG3_PCT': 0.4,
   'FTM': 0,
   'FTA': 1,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 1,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 6,
   'PLUS_MINUS': 6,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800037',
   'GAME_DATE': 'OCT 21, 2018',
   'MATCHUP': 'OKC vs. SAC',
   'WL': 'L',
   'MIN': 5,
   'FGM': 0,
   'FGA': 1,
   'FG_PCT': 0.0,
   'FG3M': 0,
   'FG3A': 1,
   'FG3_PCT': 0.0,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 1,
   'REB': 1,
   'AST': 2,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 0,
   'PTS': 0,
   'PLUS_MINUS': 5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800025',
   'GAME_DATE': 'OCT 19, 2018',
   'MATCHUP': 'OKC @ LAC',
   'WL': 'L',
   'MIN': 32,
   'FGM': 4,
   'FGA': 10,
   'FG_PCT': 0.4,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 1,
   'DREB': 1,
   'REB': 2,
   'AST': 1,
   'STL': 1,
   'BLK': 0,
   'TOV': 2,
   'PF': 0,
   'PTS': 10,
   'PLUS_MINUS': -9,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760},
  {'SEASON_ID': '22018',
   'Player_ID': 203518,
   'Game_ID': '0021800002',
   'GAME_DATE': 'OCT 16, 2018',
   'MATCHUP': 'OKC @ GSW',
   'WL': 'L',
   'MIN': 23,
   'FGM': 3,
   'FGA': 8,
   'FG_PCT': 0.375,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 0,
   'FTA': 0,
   'FT_PCT': 0.0,
   'OREB': 0,
   'DREB': 2,
   'REB': 2,
   'AST': 0,
   'STL': 0,
   'BLK': 0,
   'TOV': 0,
   'PF': 2,
   'PTS': 8,
   'PLUS_MINUS': -5,
   'VIDEO_AVAILABLE': 1,
   'TEAM_ABBREVIATION': 'OKC',
   'TEAM_ID': 1610612760}]}

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a game for each player. You must have atleast the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK','Game_ID',  'MIN', 'PTS', 'REB', 'TEAM_ABBREVIATION', 'STL'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [34]:
df = pd.DataFrame()

for person in data:
    # if the person has a gamelog, 
    if len(person['GAMELOG']) == 0:
        continue
    # create new data frame with these 3 columns
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    # create another dataframe of each player's gamelogs
    df2 = pd.DataFrame(person['GAMELOG'])
    # merge the two dataframes together so each player's info is paired with his gamelog
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    # concatenate all individual players' dataframes into 1
    df = pd.concat([df, merged])

# reset the index so that each one is unique
df.reset_index(drop=True, inplace=True)

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [56]:
# Your code here

#another way to do this:
# df.loc[df['PTS'].idxmax()]

# most points in 1 game
df[df['PTS'] == df['PTS'].max()]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
10323,James Harden,201935,1610612745,1,0,5,13,9,0.692,34,...,61,201935,7,22018,3,HOU,1610612745,3,1,W
10348,James Harden,201935,1610612745,4,0,9,20,5,0.250,38,...,61,201935,15,22018,5,HOU,1610612745,5,1,W

In [57]:
# most rebounds
df[df['REB'] == df['REB'].max()]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
23773,Karl-Anthony Towns,1626157,1610612750,3,4,18,8,3,0.375,23,...,27,1626157,27,22018,2,MIN,1610612750,3,1,W

In [58]:
# most blocks
df[df['BLK'] == df['BLK'].max()]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
21109,Mitchell Robinson,1629011,1610612752,0,9,4,0,0,0.0,3,...,4,1629011,4,22018,0,NYK,1610612752,0,1,L
25135,Hassan Whiteside,202355,1610612757,2,9,14,1,0,0.0,18,...,29,202355,20,22018,0,MIA,1610612748,1,1,W

In [59]:
# most assists

df[df['AST'] == df['AST'].max()]

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
24969,Russell Westbrook,201566,1610612745,24,0,11,4,0,0.0,22,...,24,201566,13,22018,2,OKC,1610612760,3,1,L

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [60]:
df.columns

Index(['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID_x', 'AST', 'BLK', 'DREB',
       'FG3A', 'FG3M', 'FG3_PCT', 'FGA', 'FGM', 'FG_PCT', 'FTA', 'FTM',
       'FT_PCT', 'GAME_DATE', 'Game_ID', 'MATCHUP', 'MIN', 'OREB', 'PF',
       'PLUS_MINUS', 'PTS', 'Player_ID', 'REB', 'SEASON_ID', 'STL',
       'TEAM_ABBREVIATION', 'TEAM_ID_y', 'TOV', 'VIDEO_AVAILABLE', 'WL'],
      dtype='object')

In [455]:
#your code here

grouped = df.groupby(['DISPLAY_FIRST_LAST'])
# most points
pts = grouped[['PTS']].sum()
pts.sort_values(by='PTS', ascending = False).iloc[0:1]

                     PTS
DISPLAY_FIRST_LAST
James Harden        2818

In [508]:
# most rebounds
rebs = grouped[['REB']].sum()
rebs.sort_values(by='REB', ascending = False).iloc[0:1]

                     REB
DISPLAY_FIRST_LAST
Andre Drummond      1232

In [509]:
#most blocks
blks = grouped[['BLK']].sum()
blks.sort_values(by='BLK', ascending = False).iloc[0:1]

                    BLK
DISPLAY_FIRST_LAST
Myles Turner        199

In [510]:
#most assists
asts = grouped[['AST']].sum()
asts.sort_values(by='AST', ascending = False).iloc[0:1]

                    AST
DISPLAY_FIRST_LAST
Russell Westbrook   784

## 3:
How many players played in at least 82 games last season?

In [519]:
#your code here

total_games = grouped[['Game_ID']].count()
total_games = total_games[total_games['Game_ID']>=82]
len(total_games)
# names_df[names_df['Count'] == names_df['Count'].max()]
# df.df['Game_ID'].count() > 82

21

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [414]:
# your code here
teams = df.groupby('TEAM_ABBREVIATION').sum()

# most points
teams[['PTS']].sort_values(by = 'PTS', ascending = False).iloc[0:1]

                    PTS
TEAM_ABBREVIATION
MIL                9686

In [413]:
# most rebounds

teams[['REB']].sort_values(by = 'REB', ascending = False).iloc[0:1]

                    REB
TEAM_ABBREVIATION
MIL                4078

In [409]:
# most blocks

teams[['BLK']].sort_values(by = 'BLK', ascending = False).iloc[0:1]

                   BLK
TEAM_ABBREVIATION
GSW                525

In [406]:
# most assits

teams[['AST']].sort_values(by = 'AST', ascending = False).iloc[0:1]

                    AST
TEAM_ABBREVIATION
GSW                2413

## 5:
Which team had the most players play for them last season?

In [520]:
#your code here
teams_and_games = df.groupby(['TEAM_ABBREVIATION']).nunique()[['DISPLAY_FIRST_LAST']]

teams_and_games.sort_values(by = 'DISPLAY_FIRST_LAST', ascending=False).iloc[0]

DISPLAY_FIRST_LAST    28
Name: MEM, dtype: int64

## 6:
- How many players play for more than one team last year?

- What is the most number of teams a player played for last season?

In [525]:
# df.groupby('TEAM_ID_x').sum()
players = df.groupby('DISPLAY_FIRST_LAST').nunique()[['TEAM_ABBREVIATION']]
players.max()
# players.sort_values(by = 'TEAM_ABBREVIATION', ascending=False).head(6)

TEAM_ABBREVIATION    3
dtype: int64

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [225]:
df.columns

Index(['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID_x', 'AST', 'BLK', 'DREB',
       'FG3A', 'FG3M', 'FG3_PCT', 'FGA', 'FGM', 'FG_PCT', 'FTA', 'FTM',
       'FT_PCT', 'GAME_DATE', 'Game_ID', 'MATCHUP', 'MIN', 'OREB', 'PF',
       'PLUS_MINUS', 'PTS', 'Player_ID', 'REB', 'SEASON_ID', 'STL',
       'TEAM_ABBREVIATION', 'TEAM_ID_y', 'TOV', 'VIDEO_AVAILABLE', 'WL'],
      dtype='object')

In [463]:
#your code here

# find players in more than 40 games
players = df.groupby('DISPLAY_FIRST_LAST')['PTS'].sum()[(df.groupby('DISPLAY_FIRST_LAST')['Game_ID'].count() >= 40)]
players.idxmin()

'Sindarius Thornwell'

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [392]:
#your code here

# how many players scored more than 40 points in a game?
players_over_40pg = df[(df['PTS'] > 40)]

# how many total players are there?

number_of_games = len(df)

# divide the two

len(players_over_40pg) / number_of_games

0.004214397915788667

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [554]:
# your code here

# how many players averaged more than 20 points per game?
# how many total players are there?
# divide the two

df2 = df.groupby(['DISPLAY_FIRST_LAST']).mean()
players_over_20ptsavg = len(df2[df2['PTS'] > 20])
number_of_players = len(set(df['DISPLAY_FIRST_LAST']))
# number_of_players
players_over_20ptsavg / number_of_players

0.062264150943396226

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [450]:
#your code here
players = df.groupby('DISPLAY_FIRST_LAST')['PTS'].sum()[(df.groupby('DISPLAY_FIRST_LAST')['Game_ID'].count() >= 40) & (df.groupby('DISPLAY_FIRST_LAST')['MIN'].mean() >= 15)]
players.idxmin()

'Tyson Chandler'

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [529]:
#your code here

df1 = df.groupby(['DISPLAY_FIRST_LAST','TEAM_ABBREVIATION'])[['PTS']].sum()
df2= df.groupby(['TEAM_ABBREVIATION'])[['PTS']].sum()
df3 = df1.join(df2, lsuffix='_player', rsuffix='_team')
df3['ratio'] = df3.apply(lambda x: x.PTS_player/x.PTS_team, axis=1)
df3.sort_values(by = 'ratio', ascending=False)

                                         PTS_player  PTS_team     ratio
DISPLAY_FIRST_LAST    TEAM_ABBREVIATION
James Harden          HOU                      2818      9341  0.301681
Kemba Walker          CHA                      2102      9081  0.231472
Paul George           OKC                      2159      9387  0.229999
Bradley Beal          WAS                      2099      9350  0.224492
Damian Lillard        POR                      2067      9402  0.219847
Kevin Durant          GSW                      2027      9650  0.210052
Blake Griffin         DET                      1841      8778  0.209729
Giannis Antetokounmpo MIL                      1994      9686  0.205864
Karl-Anthony Towns    MIN                      1880      9223  0.203838
Donovan Mitchell      UTA                      1829      9161  0.199651
Stephen Curry         GSW                      1881      9650  0.194922
Devin Booker          PHX                      1700      8815  0.192853
Nikola Vucevic        ORL                      1665      8800  0.189205
LaMarcus Aldridge     SAS                      1727      9156  0.188619
Joel Embiid           PHI                      1761      9445  0.186448
D'Angelo Russell      BKN                      1712      9204  0.186006
Buddy Hield           SAC                      1695      9363  0.181032
DeMar DeRozan         SAS                      1635      9156  0.178571
Russell Westbrook     OKC                      1675      9387  0.178438
Nikola Jokic          DEN                      1604      9075  0.176749
Klay Thompson         GSW                      1680      9650  0.174093
Mike Conley           MEM                      1478      8490  0.174087
Zach LaVine           CHI                      1492      8605  0.173388
Kyrie Irving          BOS                      1596      9216  0.173177
Luka Doncic           DAL                      1526      8927  0.170942
Kawhi Leonard         TOR                      1596      9384  0.170077
Trae Young            ATL                      1549      9294  0.166667
Julius Randle         NOP                      1565      9466  0.165329
LeBron James          LAL                      1505      9165  0.164212
Bojan Bogdanovic      IND                      1454      8857  0.164164
...                                             ...       ...       ...
Tahjere McCall        BKN                         4      9204  0.000435
Pau Gasol             MIL                         4      9686  0.000413
Jordan Sibert         ATL                         3      9294  0.000323
Vincent Edwards       HOU                         3      9341  0.000321
Angel Delgado         LAC                         3      9442  0.000318
Andrew Harrison       MEM                         2      8490  0.000236
DJ Stephens           MEM                         2      8490  0.000236
Yante Maten           MIA                         2      8668  0.000231
Kalin Lucas           DET                         2      8778  0.000228
Kostas Antetokounmpo  DAL                         2      8927  0.000224
Joe Chealey           CHA                         2      9081  0.000220
Zhou Qi               HOU                         2      9341  0.000214
Terrence Jones        HOU                         2      9341  0.000214
BJ Johnson            SAC                         2      9363  0.000214
Emanuel Terry         MIA                         1      8668  0.000115
Okaro White           WAS                         0      9350  0.000000
Ray Spalding          DAL                         0      8927  0.000000
Zach Lofton           DET                         0      8778  0.000000
Ron Baker             WAS                         0      9350  0.000000
Donte Grantham        OKC                         0      9387  0.000000
Kobi Simmons          CLE                         0      8567  0.000000
Ike Anigbogu          IND                         0      8857  0.000000
Tyler Zeller          ATL                         0      9294  0.000000
George King           PHX                         0      8815  0.000000
John Holland          CLE                         0      8567  0.000000
Andre Ingram          LAL                         0      9165  0.000000
Tyler Davis           OKC                         0      9387  0.000000
Jawun Evans           OKC                         0      9387  0.000000
Tyler Ulis            CHI                         0      8605  0.000000
Eric Moreland         PHX                         0      8815  0.000000

[622 rows x 3 columns]

## 12:

What is the probability that a randomly selected player had at least one game in which they scored 40 points last season.

In [576]:
# your code here

# numer = players with at least 1 game of 40 points
# total number of players = denom
# divide the 2

players = df.groupby(['DISPLAY_FIRST_LAST','Game_ID']).sum()[['PTS']]
players
players_with_40 = (players[(players['PTS'] == 40)])
unique_players = players_with_40.reset_index().nunique()['DISPLAY_FIRST_LAST']

unique_players / number_of_players

0.035849056603773584

## 13: 

A double-double is when a player records for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [584]:
#your code here

# double double = double digits in 2 of these: REB, PTS, STL, AST, BLK (10 or more in these)
# find number of games with double doubles
# divide by total number of games

df_double = df.groupby(['DISPLAY_FIRST_LAST','Game_ID']).sum()[['PTS', 'REB', 'AST']]

number_of_double= df_double[((df_double['PTS'] >= 10) & (df_double['REB'] >= 10)) | 
          ((df_double['PTS'] >= 10) & (df_double['AST'] >= 10)) |
          ((df_double['AST'] >= 10) & (df_double['REB'] >= 10 ))]

number_of_double.reset_index().nunique()['DISPLAY_FIRST_LAST'] / number_of_players

0.49056603773584906

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [580]:
#your code here

number_of_triple_doubles= df_double[(df_double['PTS'] >= 10) & (df_double['REB'] >= 10) & (df_double['AST'] >= 10)]

number_of_triple_doubles.reset_index().nunique()['DISPLAY_FIRST_LAST'] / number_of_players

0.06981132075471698

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?